# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D0OnwPWxK-FmfwIO8zfx1JPC6ya5DyKW
"""

from fastapi import FastAPI
from pydantic import BaseModel
import tensorflow as tf
import numpy as np

app = FastAPI()

personal_model = tf.saved_model.load(
    "personal_fintrack_savedmodel"
)

business_model = tf.saved_model.load(
    "business_fintrack_savedmodel"
)

"""### **INFERENCE FUNCTION**"""

personal_infer = personal_model.signatures[
    "serving_default"
]

business_infer = business_model.signatures[
    "serving_default"
]

"""### **LABELS**"""

#Personal
personal_labels = [
    "Belanja Bulanan",
    "Gaji",
    "Hiburan",
    "Makanan & Minuman",
    "Pembayaran Langganan",
    "Pulsa & Internet",
    "Tempat Tinggal",
    "Transfer Teman/Keluarga",
    "Transportasi"
]

#Business
business_labels = [
    "Biaya Bank",
    "Gaji & Karyawan",
    "Lain-lain",
    "Marketing & Promosi",
    "Modal & Investasi",
    "Operasional Kantor",
    "Pajak & Perizinan",
    "Pembelian Stok",
    "Penjualan",
    "Peralatan & Aset",
    "Piutang",
    "Software & Langganan",
    "Transportasi & Logistik",
    "Utang & Cicilan"
]

"""### **REQUEST BODY**"""

class TransactionRequest(BaseModel):
    description: str
    transaction_type: str

"""### **ROOT ENDPOINT**"""

@app.get("/")
def home():
    return {
        "message": "FinTrack API Running!"
    }

"""### **PREDICTION**"""

#Personal
@app.post("/predict/personal")
def predict_personal(data: TransactionRequest):
    text = tf.constant([
        [
            f"{data.description} {data.transaction_type}"
        ]
    ])
    prediction = personal_infer(text)
    prediction_values = list(
        prediction.values()
    )[0].numpy()
    predicted_class = np.argmax(
        prediction_values
    )
    predicted_label = personal_labels[
        predicted_class
    ]
    confidence = float(
        np.max(prediction_values)
    )
    return {
        "model": "personal_finance",
        "description": data.description,
        "transaction_type": data.transaction_type,
        "predicted_category": predicted_label,
        "confidence_score": round(confidence, 4)
    }

# Business
@app.post("/predict/business")
def predict_business(data: TransactionRequest):
    text = tf.constant([
        [
            f"{data.description} {data.transaction_type}"
        ]
    ])
    prediction = business_infer(text)
    prediction_values = list(
        prediction.values()
    )[0].numpy()
    predicted_class = np.argmax(
        prediction_values
    )
    predicted_label = business_labels[
        predicted_class
    ]
    confidence = float(
        np.max(prediction_values)
    )
    return {
        "model": "business_finance",
        "description": data.description,
        "transaction_type": data.transaction_type,
        "predicted_category": predicted_label,
        "confidence_score": round(confidence, 4)
    }